name_of_run: Baseline_log_weightednormalizedoverbatch_class1_20
model: 'Multi_L' #Multi, Multi_L, NeuralForest
data_params:
  resolved_folder_path: "/Users/irwin/Documents/GitHub/lisa-ml/data/resolved_binaries/"
  fim_folder_path: "/Users/irwin/Documents/GitHub/lisa-ml/data/fims/"
  selected_features:
    - Frequency_mHz
    - Amplitude_log10
    - FrequencyDerivative_log10
    - SNR
    - Eccentricity
  n_samples_class0: 1
  n_samples_class1: 20
  ecc_0_only: False
  use_custom_weights: True
  test_seed_val: 1
  val_seed_val: 1
  training_batch_size: 128
  inference_batch_size: 128
  frequency_range: null #Include all data above and equals to n mHz, if upsampling is applied, filtering will be applied before the upsampling
training_params:
  num_epochs: 100
  lr: 0.001
  focal_loss:
    gamma: 2.0
    alpha: 0.25
evaluation_threshold: 0.5
test: False
  